# Generated by Django 3.2.3 on 2021-08-07 20:23

import colorfield.fields
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageCustomisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styling_name', models.CharField(default='Default', max_length=55)),
                ('about_section_title', models.CharField(max_length=100)),
                ('about_section_blurb', models.TextField(default='Short blurb', max_length=250)),
                ('about_section_content', djrichtextfield.models.RichTextField()),
                ('about_section_left_image', models.ImageField(blank=True, null=True, upload_to='about_page_images')),
                ('about_section_right_image', models.ImageField(blank=True, null=True, upload_to='about_page_images')),
                ('contact_section_title', models.CharField(max_length=100)),
                ('contact_section_blurb', models.TextField(default='Short blurb', max_length=250)),
                ('contact_card_title', models.CharField(default='Business Name', max_length=100)),
                ('contact_card_info', djrichtextfield.models.RichTextField()),
                ('contact_card_image', models.ImageField(blank=True, null=True, upload_to='about_page_images/contact_page_images')),
                ('contact_card_background_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('contact_card_text_color', colorfield.fields.ColorField(default='#00000', max_length=18)),
                ('contact_card_border', models.TextField(choices=[('add-contact-card-border', 'Add Border'), ('no-border', 'No Border')], default='no-border')),
                ('border_color', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('twitter_link', models.URLField(default='https://twitter.com/')),
                ('linkedin_link', models.URLField(default='https://linkedin.com/')),
                ('facebook_link', models.URLField(default='https://facebook.com/')),
                ('instagram_link', models.URLField(default='https://instagram.com/')),
                ('do_not_display', models.BooleanField(default=False, help_text='**Check this box to hide this specific styling.', verbose_name='Do not display')),
            ],
            options={
                'verbose_name_plural': '  About Page',
            },
        ),
        migrations.CreateModel(
            name='FooterCustomisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styling_name', models.CharField(default='Default', max_length=55)),
                ('background_color', colorfield.fields.ColorField(default='#333333', max_length=18)),
                ('text_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('twitter_link', models.URLField(blank=True, default='https://twitter.com/', null=True)),
                ('linkedin_link', models.URLField(blank=True, default='https://linkedin.com/', null=True)),
                ('facebook_link', models.URLField(blank=True, default='https://facebook.com/', null=True)),
                ('instagram_link', models.URLField(blank=True, default='https://instagram.com/', null=True)),
                ('social_media_icon_colors', colorfield.fields.ColorField(default='FFFFFF', max_length=18)),
                ('do_not_display', models.BooleanField(default=False, help_text='**Check this box to hide this specific styling.', verbose_name='Do not display')),
            ],
            options={
                'verbose_name_plural': ' Footer',
            },
        ),
        migrations.CreateModel(
            name='GlobalSiteStyling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_site_styles', models.CharField(help_text='Give these global styles a name...', max_length=20)),
                ('base_background_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('base_font_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('all_icon_colors', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('primary_button_base_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('primary_button_text_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('secondary_button_base_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('secondary_button_text_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('pop_up_background_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('pop_up_text_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('dropdown_menu_background_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('dropdown_menu_text_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('do_not_display', models.BooleanField(default=False, help_text='Check this box to hide this specific styling.', verbose_name='Do not display')),
            ],
            options={
                'verbose_name_plural': '        Global Page Styles',
            },
        ),
        migrations.CreateModel(
            name='HeaderCustomisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_styling', models.CharField(default='Default Styling', max_length=55)),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('header_background_color', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('search_icon_color', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('search_icon_background_color', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('small_banner_text', models.CharField(default='Welcome', max_length=100)),
                ('small_banner_background_color', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('small_banner_text_color', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('do_not_display', models.BooleanField(default=False, help_text='CHECK THIS BOX TO HIDE THIS SPECIFIC STYLING.', verbose_name='Do not display')),
            ],
            options={
                'verbose_name_plural': '      Header',
            },
        ),
        migrations.CreateModel(
            name='HomePageCustomisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page_styling', models.CharField(default='Name This Styling...', max_length=35)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_page_images')),
                ('main_page_text', djrichtextfield.models.RichTextField()),
                ('main_page_text_alignment', models.TextField(choices=[('text-align__center', 'Center'), ('text-align__left', 'Left'), ('text-align__right', 'Right')], default='text-align__left')),
                ('main_page_text_color', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('button_text', models.CharField(default='Shop Now', max_length=15)),
                ('button_text_color', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('button_background_color', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('main_page_button_alignment', models.TextField(choices=[('text-align__center', 'Center'), ('text-align__left', 'Left'), ('text-align__right', 'Right')], default='text-align__left')),
                ('do_not_display', models.BooleanField(default=False, help_text='CHECK THIS BOX TO HIDE THIS SPECIFIC STYLING.', verbose_name='Do not display')),
            ],
            options={
                'verbose_name_plural': '     Home Page',
            },
        ),
        migrations.CreateModel(
            name='ProductsPageCustomisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_page_styling', models.CharField(default='Default Product Page Styling', max_length=55)),
                ('category_tag_border_color', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('category_tag_text_color', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('product_card_background_color', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('add_card_border', models.TextField(choices=[('add-border', 'Add Border'), ('no-border', 'No Border')], default='no-border')),
                ('border_color', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('product_card_font_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('product_card_icon_color', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('product_quantity_buttons', colorfield.fields.ColorField(default='#FFFFFFFF', help_text='**Product Display Page', max_length=18)),
                ('do_not_display', models.BooleanField(default=False, help_text='**Check this box to hide this specific styling.', verbose_name='Do not display')),
            ],
            options={
                'verbose_name_plural': '    Products Page',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsPageCustomisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients_name', models.CharField(max_length=100)),
                ('twitter_link', models.URLField(blank=True, default='https://twitter.com/', null=True)),
                ('linkedin_link', models.URLField(blank=True, default='https://linkedin.com/', null=True)),
                ('facebook_link', models.URLField(blank=True, default='https://facebook.com/', null=True)),
                ('instagram_link', models.URLField(blank=True, default='https://instagram.com/', null=True)),
                ('testimonial', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name_plural': '  Testimonials Page',
            },
        ),
    ]
