# Generated by Django 3.2.3 on 2021-08-22 16:00

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialspagecustomisation',
            name='card_background_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='testimonialspagecustomisation',
            name='card_border',
            field=models.TextField(blank=True, choices=[('add-border', 'Add Border'), ('no-border', 'No Border')], default='no-border', null=True),
        ),
        migrations.AddField(
            model_name='testimonialspagecustomisation',
            name='card_border_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__left', 'Left'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__left', 'Left'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
    ]
