# Generated by Django 3.2.3 on 2021-08-16 22:27

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0002_auto_20210816_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctabanner',
            name='add_border',
            field=models.TextField(choices=[('add-border', 'Add Border'), ('no-border', 'Remove Border')], default='no-border'),
        ),
        migrations.AddField(
            model_name='ctabanner',
            name='banner_background_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='ctabanner',
            name='border_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__center', 'Center'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__center', 'Center'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
    ]
