# Generated by Django 3.2.3 on 2021-08-31 17:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0002_auto_20210831_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsitestyling',
            name='primary_button_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='globalsitestyling',
            name='secondary_button_base_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
