# Generated by Django 3.2.3 on 2021-08-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0002_auto_20210828_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='headercustomisation',
            name='edit_banner_buttons',
            field=models.CharField(blank=True, default='/superadmin/page_customisations/headercustomisation/1/change/', max_length=120, null=True),
        ),
    ]
