# Generated by Django 3.2.3 on 2021-08-23 14:33

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0005_auto_20210822_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients_name', models.CharField(max_length=100)),
                ('testimonial', djrichtextfield.models.RichTextField(max_length=500)),
                ('customers_rating', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'verbose_name_plural': ' Add Testimonial',
            },
        ),
        migrations.RemoveField(
            model_name='testimonialspagecustomisation',
            name='customers_rating',
        ),
        migrations.RemoveField(
            model_name='testimonialspagecustomisation',
            name='recipients_name',
        ),
        migrations.RemoveField(
            model_name='testimonialspagecustomisation',
            name='testimonial',
        ),
        migrations.AddField(
            model_name='testimonialspagecustomisation',
            name='do_not_display',
            field=models.BooleanField(default=False, help_text='**Check this box to hide this specific styling.', verbose_name='Do not display'),
        ),
        migrations.AddField(
            model_name='testimonialspagecustomisation',
            name='style_name',
            field=models.CharField(default='Defaul', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__center', 'Center'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__center', 'Center'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
    ]
