# Generated by Django 3.2.3 on 2021-08-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0005_aboutpagecustomisation_do_not_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecustomisation',
            name='about_blurb',
            field=models.TextField(default='Short blurb', max_length=250),
        ),
        migrations.AddField(
            model_name='aboutpagecustomisation',
            name='about_page_content',
            field=models.TextField(default='About You...', max_length=250),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__center', 'Center'), ('text-align__left', 'Left')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__center', 'Center'), ('text-align__left', 'Left')], default='text-align__left'),
        ),
    ]
