# Generated by Django 3.2.3 on 2021-08-23 19:19

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0006_auto_20210823_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialspagecustomisation',
            name='form_background_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__center', 'Center'), ('text-align__left', 'Left')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__center', 'Center'), ('text-align__left', 'Left')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='testimonialspagecustomisation',
            name='card_border_color',
            field=colorfield.fields.ColorField(blank=True, default='#000000', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='testimonialspagecustomisation',
            name='star_rating_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFE231', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='testimonialspagecustomisation',
            name='style_name',
            field=models.CharField(default='Default', max_length=100),
        ),
    ]
