# Generated by Django 3.2.3 on 2021-08-31 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0006_auto_20210831_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='cta_card_1',
            field=models.ForeignKey(blank=True, help_text='Click the + button to create a new CTA card.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cta_card_1', to='page_customisations.ctacard'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='cta_card_2',
            field=models.ForeignKey(blank=True, help_text='Click the + button to create a new CTA card.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cta_card_2', to='page_customisations.ctacard'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='home_page_styling',
            field=models.CharField(default='Default Home Page Styling', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__right', 'Right'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__right', 'Right'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
    ]
