# Generated by Django 3.2.3 on 2021-08-23 20:00

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0007_auto_20210823_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialspagecustomisation',
            name='button_border',
            field=models.TextField(blank=True, choices=[('add-border', 'Add Border'), ('no-border', 'No Border')], default='no-border', null=True),
        ),
        migrations.AddField(
            model_name='testimonialspagecustomisation',
            name='form_font_color',
            field=colorfield.fields.ColorField(blank=True, default='#00000', max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='testimonialspagecustomisation',
            name='submit_button_background_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='testimonialspagecustomisation',
            name='submit_button_border_color',
            field=colorfield.fields.ColorField(blank=True, default='#000000', max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='testimonialspagecustomisation',
            name='submit_button_label',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='testimonialspagecustomisation',
            name='submit_button_label_color',
            field=colorfield.fields.ColorField(blank=True, default='#000000', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__center', 'Center'), ('text-align__left', 'Left'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__center', 'Center'), ('text-align__left', 'Left'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='testimonialspagecustomisation',
            name='form_background_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', max_length=18, null=True),
        ),
    ]
