# Generated by Django 3.2.3 on 2021-08-31 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0007_auto_20210831_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='cta_banner',
            field=models.ForeignKey(blank=True, help_text='Click the + button to create a new CTA banner.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cta_banner', to='page_customisations.ctabanner'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__center', 'Center'), ('text-align__left', 'Left'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__center', 'Center'), ('text-align__left', 'Left'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
    ]
