# Generated by Django 3.2.3 on 2021-08-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0008_auto_20210831_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctacard',
            old_name='cta_title_text_color',
            new_name='cta_text_color',
        ),
        migrations.AlterField(
            model_name='ctacard',
            name='cta_title',
            field=models.CharField(default='Default CTA Card Styling.', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__center', 'Center'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__center', 'Center'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
    ]
