# Generated by Django 3.2.3 on 2021-08-16 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0008_auto_20210816_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecustomisation',
            name='cta_card',
        ),
        migrations.AddField(
            model_name='homepagecustomisation',
            name='cta_card_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cta_card_1', to='page_customisations.ctacard'),
        ),
        migrations.AddField(
            model_name='homepagecustomisation',
            name='cta_card_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cta_card_2', to='page_customisations.ctacard'),
        ),
    ]
