# Generated by Django 3.2.3 on 2021-08-16 15:26

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_name_category_url_name'),
        ('page_customisations', '0009_auto_20210816_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctacard',
            old_name='card_name',
            new_name='cta_title',
        ),
        migrations.RemoveField(
            model_name='ctacard',
            name='text',
        ),
        migrations.AddField(
            model_name='ctacard',
            name='button_url_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='button_url', to='products.category'),
        ),
        migrations.AddField(
            model_name='ctacard',
            name='cta_text',
            field=djrichtextfield.models.RichTextField(default='Default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__left', 'Left'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__left', 'Left'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
    ]
