# Generated by Django 3.2.3 on 2021-08-23 20:10

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0009_auto_20210823_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialspagecustomisation',
            name='form_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='testimonialspagecustomisation',
            name='testimonial_form_blurb',
            field=djrichtextfield.models.RichTextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__left', 'Left'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__left', 'Left'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
    ]
