# Generated by Django 3.2.3 on 2021-08-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0010_auto_20210816_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctacard',
            name='button_text',
            field=models.CharField(default='Shop Now', max_length=25),
            preserve_default=False,
        ),
    ]
