# Generated by Django 3.2.3 on 2021-08-31 17:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0011_auto_20210831_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footercustomisation',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter your contact number to be displayed in the footer.', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='footercustomisation',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter your email to be displayed in the footer.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__center', 'Center'), ('text-align__left', 'Left')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__center', 'Center'), ('text-align__left', 'Left')], default='text-align__left'),
        ),
    ]
