# Generated by Django 3.2.3 on 2021-08-17 17:38

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0011_auto_20210817_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headercustomisation',
            name='small_banner_text',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
