# Generated by Django 3.2.3 on 2021-08-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0011_auto_20210802_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecustomisation',
            name='contact_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_page_images/contact_page_images'),
        ),
        migrations.AddField(
            model_name='aboutpagecustomisation',
            name='contact_section_blurb',
            field=models.TextField(default='Short blurb', max_length=250),
        ),
        migrations.AddField(
            model_name='aboutpagecustomisation',
            name='contact_section_info',
            field=models.TextField(default='Short blurb', max_length=500),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__left', 'Left'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__left', 'Left'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
    ]
