# Generated by Django 3.2.3 on 2021-08-16 16:48

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0012_auto_20210816_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecustomisation',
            name='cta_banner_text',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='homepagecustomisation',
            name='cta_banner_title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__center', 'Center'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__center', 'Center'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
    ]
