# Generated by Django 3.2.3 on 2021-08-16 16:59

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0013_auto_20210816_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecustomisation',
            name='cta_banner_text',
        ),
        migrations.AddField(
            model_name='homepagecustomisation',
            name='cta_button_label',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='homepagecustomisation',
            name='cta_button_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='cta_banner_title',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__left', 'Left'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__left', 'Left'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
    ]
