# Generated by Django 3.2.3 on 2021-08-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0019_auto_20210803_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecustomisation',
            name='facebook_link',
            field=models.URLField(default='Link to your Facebook Account'),
        ),
        migrations.AddField(
            model_name='aboutpagecustomisation',
            name='instagram_link',
            field=models.URLField(default='Link to your Instagram Account'),
        ),
        migrations.AddField(
            model_name='aboutpagecustomisation',
            name='linkedin_link',
            field=models.URLField(default='Link to your LinkedIn Account'),
        ),
        migrations.AddField(
            model_name='aboutpagecustomisation',
            name='twitter_link',
            field=models.URLField(default='Link to your Twitter Account'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__center', 'Center'), ('text-align__right', 'Right'), ('text-align__left', 'Left')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__center', 'Center'), ('text-align__right', 'Right'), ('text-align__left', 'Left')], default='text-align__left'),
        ),
    ]
