# Generated by Django 3.2.3 on 2021-09-12 13:23

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0021_auto_20210912_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctabanner',
            name='button_border',
            field=models.TextField(choices=[('add-border', 'Add Border'), ('no-border', 'Remove Border')], default='no-border'),
        ),
        migrations.AddField(
            model_name='ctabanner',
            name='card_button_text_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__right', 'Right'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__right', 'Right'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
    ]
