# Generated by Django 3.2.3 on 2021-08-04 10:29

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0026_auto_20210804_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
