# Generated by Django 3.2.3 on 2021-09-15 19:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0026_auto_20210915_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialspagecustomisation',
            name='form_field_placeholder_color',
            field=colorfield.fields.ColorField(blank=True, default='#000000', max_length=18, null=True),
        ),
    ]
