# Generated by Django 3.2.3 on 2021-09-15 19:25

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0027_testimonialspagecustomisation_form_field_placeholder_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialspagecustomisation',
            name='form_field_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#000000', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__center', 'Center'), ('text-align__left', 'Left'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__center', 'Center'), ('text-align__left', 'Left'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
    ]
