# Generated by Django 3.2.3 on 2021-09-18 16:25

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0030_auto_20210918_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialspagecustomisation',
            name='form_title',
            field=djrichtextfield.models.RichTextField(blank=True, default='', max_length=300, null=True),
        ),
    ]
