# Generated by Django 3.2.3 on 2021-08-05 16:07

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0034_auto_20210804_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterCustomisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styling_name', models.CharField(default='Default', max_length=55)),
                ('background_color', colorfield.fields.ColorField(default='#333333', max_length=18)),
                ('text_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('twitter_link', models.URLField(default='https://twitter.com/')),
                ('linkedin_link', models.URLField(default='https://linkedin.com/')),
                ('facebook_link', models.URLField(default='https://facebook.com/')),
                ('instagram_link', models.URLField(default='https://instagram.com/')),
                ('social_media_icon_colors', colorfield.fields.ColorField(default='FFFFFF', max_length=18)),
                ('do_not_display', models.BooleanField(default=False, help_text='**Check this box to hide this specific styling.', verbose_name='Do not display')),
            ],
            options={
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__left', 'Left'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__left', 'Left'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
    ]
