# Generated by Django 3.2.3 on 2021-08-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('your_thoughts', models.CharField(max_length=450)),
                ('twitter_link', models.URLField(blank=True, default='https://twitter.com/', null=True)),
                ('linkedin_link', models.URLField(blank=True, default='https://linkedin.com/', null=True)),
                ('facebook_link', models.URLField(blank=True, default='https://facebook.com/', null=True)),
                ('instagram_link', models.URLField(blank=True, default='https://instagram.com/', null=True)),
            ],
        ),
    ]
