# Generated by Django 3.2.3 on 2021-08-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_alter_testimonial_date_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='date_received',
        ),
    ]
