# Generated by Django 3.2.3 on 2021-08-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_remove_testimonial_date_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='other_social_media_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='facebook_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='instagram_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='linkedin_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='twitter_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
