# Generated by Django 3.2.3 on 2021-08-19 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0006_alter_testimonial_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
