# Generated by Django 3.2.3 on 2021-08-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0007_testimonial_date_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='upload_image',
            field=models.ImageField(blank=True, help_text='Show us an image of your purchased product', null=True, upload_to='https://s3.eu-west-2.amazonaws.com/nueui-ecommerce-template/'),
        ),
    ]
