# Generated by Django 3.2.3 on 2021-08-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_to_cta_banner',
            field=models.BooleanField(default=False),
        ),
    ]
