# Generated by Django 3.2.3 on 2021-08-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='small_image_1',
            new_name='alternative_image_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='small_image_2',
            new_name='alternative_image_2',
        ),
    ]
