# Generated by Django 3.2.3 on 2021-08-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeandprice',
            name='size_price_name',
            field=models.TextField(default='', max_length=25),
        ),
    ]
