# Generated by Django 3.2.3 on 2021-09-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_add_to_cta_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SizePrice',
        ),
    ]
