# Generated by Django 3.2.3 on 2021-08-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210823_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alternative_image_1',
            field=models.ImageField(blank=True, help_text='This will be the first image in the carousel.', null=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='alternative_image_2',
            field=models.ImageField(blank=True, help_text='This will be the second image in the carousel.', null=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_product_image',
            field=models.ImageField(default='', help_text='This will be the main image in the carousel.', upload_to='product_images'),
        ),
    ]
