# Generated by Django 3.2.3 on 2021-08-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='main_product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='small_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='small_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='small_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
