# Generated by Django 3.2.3 on 2021-08-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210806_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='small_image_3',
        ),
    ]
